service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:977153740074:table/TokensUser

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  postTokenUser:
    handler: src/postTokenUser.postTokenUser
    events:
      - httpApi: 
        path: /tokenuser
        method: post
  getTokenUsers:
    handler: src/getTokenUsers.getTokenUsers
    events:
      - httpApi: 
        path: /tokenusers
        method: get
  getTokenUser:
    handler: src/getTokenUser.getTokenUser
    events:
      - httpApi: 
        path: /tokenuser/{userId}
        method: get
      
resources:
  Resources:
    TokensUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TokensUsers
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
